formatter: markdown

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Footer }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Example

  ```hcl
  {{ include "examples/locals.tf" }}
  ```

  ```hcl
  {{ include "examples/variables.tf" }}
  ```

  ```hcl
  {{ include "examples/example.tf" }}
  ```

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true